package debt

const (
	DebtMenuTitle      = "📋 Меню долгов"
	EnterDescription   = "Введите описание:"
	EnterAmount        = "Введите сумму (целое число):"
	EnterDate          = "Укажите дату (ДД.ММ.ГГГГ) или выберите:"
	DebtAdded          = "✅ Долг добавлен"
	DebtUpdated        = "✅ Долг обновлен"
	DebtDeleted        = "✅ Долг удален"
	NoDebts            = "Нет активных долгов"
	SelectDebtToEdit   = "Выберите долг для редактирования:"
	SelectDebtToDelete = "Выберите долг для удаления:"
	InvalidAmount      = "❌ Неверная сумма"
	InvalidDate        = "❌ Неверная дата"
	ActionCancelled    = "🚫 Действие отменено"
)

var debtTitles = []string{
	"💢 WHO THE HELL DO THESE DEBTS THINK THEY ARE?!",
	"💢 SINCE WHEN DID DEBTS DARE CHALLENGE US?!",
	"💢 THESE DEBTS WON'T KNOW WHAT DRILLED THEM!",
	"💢 DEBTS? WE'LL PIERCE THROUGH EVERY LAST ONE!",
	"💢 OUR SPIRAL POWER CRUSHES DEBT WEAKNESS!",
	"💢 LET'S SEE YOU GRIT THOSE DEBTS!",
	"💢 DEBTS ARE JUST ANOTHER CEILING TO PIERCE!",
	"💢 MY DRILL IS THE DRILL THAT WILL BURY THESE DEBTS!",
	"💢 ONE MILLION PERCENT DEBT DESTRUCTION!",
	"💢 WE EVOLVE BEYOND OUR DEBTS EVERY DAY!",
	"💢 DEBTS CAN'T MEASURE THE HUMAN SPIRIT!",
	"💢 ANTI-SPIRAL DEBT? NOT ON OUR WATCH!",
}

var motivationalPhrases = []string{
	"💢 JUST WHO THE HELL DO YOU THINK WE ARE?!",
	"💢 BELIEVE IN THE ME THAT BELIEVES IN YOU!",
	"💢 KICK REASON TO THE CURB AND DO THE IMPOSSIBLE!",
	"💢 LET'S SEE YOU GRIT THOSE TEETH!",
	"💢 DON'T BELIEVE IN YOURSELF! BELIEVE IN ME WHO BELIEVES IN YOU!",
	"💢 MY DRILL IS THE DRILL THAT CREATES THE HEAVENS!",
	"💢 WHO THE HELL DO YOU THINK I AM?! I'M SIMON! I'M NOT MY BRO!",
	"💢 WE EVOLVE BEYOND THE PERSON WE WERE A MINUTE BEFORE!",
	"💢 THE POWER TO CHANGE DESTINY IS IN YOUR HANDS!",
	"💢 I'M NOT MY BROTHER! I'M ME! SIMON THE DIGGER!",
	"💢 ONE MILLION PERCENT OF YOUR POWER!",
	"💢 WE'RE GONNA COMBINE ALL OUR POWER AND PIERCE THE HEAVENS!",
	"💢 THE HUMAN SPIRIT CAN'T BE MEASURED!",
	"💢 WE FIGHT THE POWER THAT KEEPS US DOWN!",
	"💢 PIERCE THE HEAVENS WITH YOUR DRILL!",
	"💢 A REAL MAN DOESN'T DIE EVEN WHEN HE'S KILLED!",
	"💢 THE ONLY TIME WE HAVE IS THE MOMENT WE'RE LIVING NOW!",
	"💢 DRILLS THAT PIERCE HEAVENS, GIGA DRILL BREAKER!",
	"💢 WE'LL OPEN A PATH WITH OUR OWN HANDS!",
	"💢 IF THERE'S A WALL IN OUR WAY, WE SMASH IT DOWN!",
	"💢 YOU CAN DO IT! JUST PUSH THROUGH!",
	"💢 THE SPIRAL KINGDOM SHALL RISE AGAIN!",
	"💢 BELIEVE IN THE YOU WHO BELIEVES IN YOURSELF!",
	"💢 OUR WILL IS STRONGER THAN ANY GRAVITY!",
	"💢 WE'LL SHOW YOU WHAT HUMAN WILLPOWER CAN DO!",
	"💢 YOUR DRILL IS THE DRILL THAT WILL PIERCE THE DEBTS!",
	"💢 DEBTS ARE JUST ANOTHER WALL TO BREAK THROUGH!",
	"💢 SHOW YOUR DEBTS THE POWER OF THE SPIRAL!",
	"💢 NOTHING IN THIS WORLD CAN DEFEAT THE HUMAN SPIRIT!",
	"💢 WE'LL TURN THOSE DEBTS INTO COSMIC DUST!",
}

var noDebtsPhrases = []string{
	"YOUR SPIRAL POWER HAS CRUSHED ALL DEBTS!",
	"CLEAN SLATE! JUST LIKE THE BLUE SKY ABOVE!",
	"NO DEBTS DARE CHALLENGE YOU NOW!",
	"YOUR DRILL HAS PIERCED THROUGH ALL OBSTACLES!",
	"THE ANTI-SPIRALS OF DEBT HAVE BEEN DEFEATED!",
}
