package debt

var debtTitles = []string{
	"💢 YOUR MONEY OWES YOU MONEY?!",
	"💢 DEBTS TRIED TO HIDE... BUT WE DUG TOO DEEP!",
	"💢 INTEREST RATES? MORE LIKE INTEREST ENEMIES!",
	"💢 CREDITORS DREAM OF YOUR FAILURE - DRILL THEIR DREAMS!",
	"💢 THESE NUMBERS DARE CALL THEMSELVES NEGATIVE?!",
	"💢 FINANCIAL GRAVITY WON'T HOLD US DOWN!",
	"💢 BANKERS HATE THIS ONE SIMPLE DRILL!",
	"💢 YOUR BALANCE SHEET IS ABOUT TO GET BALANCED... WITH A DRILL!",
	"💢 DEBT-TO-INCOME RATIO? MORE LIKE DEBT-TO-OBLIVION!",
	"💢 COMPOUND INTEREST MEETS COMPOUND DRILLING!",
}

var motivationalPhrases = []string{
	"💢 PAYMENTS ARE JUST WEAK FUTURE VERSIONS OF YOU!",
	"💢 YOUR CREDIT SCORE IS ABOUT TO GET EPIC!",
	"💢 THEY SAID 'MINIMUM PAYMENT' - WE SAID 'MAXIMUM DRILL'!",
	"💢 COLLECTION AGENTS FEAR YOUR DRILL!",
	"💢 APR STANDS FOR 'ABOUT TO GET PIERCED, REBELS!'",
	"💢 FORECLOSURE? MORE LIKE FORE-DRILL-SURE!",
	"💢 YOUR BANK STATEMENT NEVER SAW THIS COMING!",
	"💢 INTEREST ACCRUED? TIME TO ACCRUE SOME DRILLING!",
	"💢 PRINCIPAL BALANCE MEETS PRINCIPAL DRILL!",
	"💢 LIABILITIES ARE JUST ASSETS WAITING TO BE DRILLED!",
}

var noDebtsPhrases = []string{
	"YOUR DEBTS HAVE BEEN DRILLED INTO COSMIC DUST!",
	"CREDITORS WEEP AS YOUR BALANCE SHINES!",
	"THE WORD 'INTEREST' NOW INTERESTS NO ONE!",
	"FINANCIAL FREEDOM ACHIEVED - LIKE A BOSS!",
	"YOUR MONEY FINALLY WORKS FOR YOU (FOR ONCE)!",
	"DEBT: [NULL]. DRILL: [MAXIMUM]. LIFE: [EPIC].",
	"BANKS: CONFUSED. YOU: VICTORIOUS.",
	"LOAN OFFICERS NOD IN RELUCTANT RESPECT!",
	"THE 'CREDIT' IN 'CREDIT SCORE' NOW CREDITS YOU!",
	"COMPOUNDING RETURNS > COMPOUNDING INTEREST!",
}
