package manager

// COMMAND HANDLER
const (
	MsgCMDStart = "🌀 SPIRAL CORE — READY\n\n" +
		"🌀 STATUS: 🔋 ACTIVE\n\n" +
		"🌀 TARGET: YOUR LIMITS\n\n" +
		"🌀 DEPLOYED:\n" +
		"  💢 DEBT DRILL — ONLINE\n\n" +
		"🌀 SOON:\n" +
		"  🍳 KITCHEN DRILL\n" +
		"  💪 GYM DRILL\n" +
		"  📅 TASK DRILL\n\n" +
		"🌀 HEAR IT?\n" +
		"🌀 THE DRILL IS TURNING...\n\n"

	MsgCMDHelp = "💢 SPIRAL COMMAND TRANSMISSION RECEIVED 💢\n\n" +
		"🌀 /start — ACTIVATE MAIN DRILL\n" +
		"📡 /help — DISPLAY COMBAT MANUAL\n" +
		"📝 /debt — DEBT DRILL PROTOCOL MANUAL\n" +
		"🍳 /recipe — KITCHEN DRILL PROTOCOL (SOON)\n" +
		"💪 /gym — HYPERTROPHY DRILL PROTOCOL (SOON)\n" +
		"📅 /task — TASK DRILL PROTOCOL (SOON)\n\n" +
		"THE POWER TO CHANGE YOUR LIFE\n" +
		"IS THE POWER TO DRILL!\n\n" +
		"💢 WHO THE HELL DO YOU THINK YOU ARE?!"

	MsgCMDDebt = "🌀 DEBT DRILL PROTOCOL - OPERATIONAL 🌀\n\n" +
		"💥 THIS MODULE ALLOWS YOU TO:\n\n" +
		"• 📝 CREATE SPIRAL CONTRACTS (DEBTS)\n" +
		"• 💸 TRACK SPIRAL POWER (AMOUNT OWED)\n" +
		"• ⏳ SET D-DAY (RETURN DEADLINE)\n" +
		"• 💢 PAY IN PARTS — EACH PAYMENT IS A SPIRAL STRIKE!\n" +
		"• ☠️ ERASE CONTRACTS FROM EXISTENCE\n" +
		"• 📊 VIEW ALL CONTRACTS IN DRILL LOG\n\n" +
		"💥 YOUR DEBTS ARE NOT LIMITS —\n" +
		"THEY ARE TARGETS FOR YOUR DRILL TO PIERCE!\n\n" +
		"🌀 DEPLOY MODULE FROM MAIN MENU TO BEGIN."

	MsgCMDRecipe = "🍲 KITCHEN DRILL PROTOCOL - STANDBY 🍲\n\n" +
		"⚡ THIS MODULE WILL ALLOW YOU TO:\n\n" +
		"• 🍅 PLAN MEALS & RECIPES\n" +
		"• 🛒 CALCULATE GROCERY LIST\n" +
		"• 🔬 TRACK BZHU (MACROS)\n" +
		"• 🔥 OPTIMIZE CALORIC INTAKE\n\n" +
		"💥 YOUR KITCHEN IS NOT A PANTRY —\n" +
		"IT'S A BATTLEFIELD FOR NUTRITIONAL SUPERIORITY!\n\n" +
		"🚀 COMING SOON — PREPARE FOR LAUNCH!"

	MsgCMDGym = "🏋️ HYPERTROPHY DRILL PROTOCOL - STANDBY 🏋️\n\n" +
		"💥 THIS MODULE WILL ALLOW YOU TO:\n\n" +
		"• 💪 LOG WORKOUTS & EXERCISES\n" +
		"• 🔁 TRACK SETS, REPS, WEIGHT\n" +
		"• 📈 MONITOR PROGRESS & GROWTH\n" +
		"• 🚨 DETECT STAGNATION PATTERNS\n\n" +
		"💥 YOUR GYM IS NOT A ROOM —\n" +
		"IT'S A LABORATORY FOR MUSCLE SPIRALIZATION!\n\n" +
		"🚀 COMING SOON — PREPARE FOR GROWTH OVERDRIVE!"

	MsgCMDTask = "📅 TASK DRILL PROTOCOL - STANDBY 📅\n\n" +
		"⚡ THIS MODULE WILL ALLOW YOU TO:\n\n" +
		"• 🎯 CREATE & MANAGE TASKS\n" +
		"• ⏳ SET DEADLINES & REMINDERS\n" +
		"• 🚀 PRIORITIZE MISSIONS\n" +
		"• ☠️ ANNIHILATE PROCRASTINATION\n\n" +
		"💥 YOUR TO-DO LIST IS NOT A CHORE —\n" +
		"IT'S A SPIRAL TARGET FOR PIERCING!\n\n" +
		"🚀 COMING SOON — PREPARE FOR LIMIT-BREAK!"

	MainMenuButtonGeneral = "🌀 DEPLOY COMMAND CENTER 🌀"

	InvalidCommand = "🚨 COMMAND REJECTED BY SPIRAL CORE! 💢\n\n" +
		"🌀 THIS DRILL ONLY RESPONDS TO PROPER ORDERS!\n" +
		"⚡ CHECK YOUR INPUT AND ATTACK AGAIN!\n\n" +
		"💢 YOUR KEYBOARD IS NOT THE DRILL THAT PIERCES THE HEAVENS!"
)

// MAIN MENU
const (
	MsgMainMenu = SpiralDelimiter +
		"🌀 SPIRAL CORE IS ONLINE. THE DRILL IS TURNING.\n\n" +
		"⚡ YOUR LIMITS HAVE BEEN TARGETED AND LOCKED.\n\n" +
		"🌀 DRILL COMMANDER, THE BATTLE BEGINS\n" +
		"DEPLOY YOUR FIRST PROTOCOL NOW:\n\n" +
		SpiralDelimiter

	DebtModuleButton   = "💢 DEBT DRILL — LIVE"
	RecipeModuleButton = "🍳 KITCHEN DRILL — BOOT"
	GymModuleButton    = "💪 GYM DRILL — BOOT"
	TasksModuleButton  = "📅 TASK DRILL — BOOT"
)

// GENERAL
const (
	FailedToCreateKeyboard = "💢 DRILL CONTROL PANEL CRASHED! 💢\n\n" +
		"🚨 FAILED TO BUILD BUTTON MATRIX\n" +
		"🌀 INITIALIZING EMERGENCY PROTOCOLS..."

	ButtonOnlyMode = "🚨 DRILL COMMAND SYSTEM LOCKED! 🚨\n\n" +
		"💢 YOUR WORDS ARE WEAKER THAN A BANK'S PROMISES!\n" +
		"🌀 THIS IS BUTTON-ONLY COMBAT MODE!\n" +
		"⚡ REAL SPIRAL WARRIORS USE THE DRILL INTERFACE!\n\n" +
		"💢 ENGAGE TACTICAL COMMAND BUTTONS BELOW!\n" +
		"⚔️ YOUR KEYBOARD IS NOT THE DRILL THAT WILL PIERCE THE HEAVENS!"

	InvalidStep = "💥 ABNORMAL DRILLING SEQUENCE DETECTED! 💥\n\n" +
		"🌀 UNKNOWN STEP: %v\n" +
		"🚨 SPIRAL MATRIX COMPROMISED!\n" +
		"⚡ REALIGNING TEMPORAL DRILL PATH..."

	InvalidEventType = "💥 UNIDENTIFIED EVENT SIGNAL! 🚨\n\n" +
		"⚡ THIS DRILL DOESN'T RECOGNIZE THIS THREAT\n" +
		"💢 DEPLOY STANDARD PROTOCOLS ONLY!\n" +
		"🌀 ABORTING NON-COMPLIANT INPUT!"

	SessionLost = "💥 SPIRAL CONNECTION LOST! 🚨\n\n" +
		"🌀 YOUR DRILL SESSION VANISHED INTO THE VOID\n" +
		"⚡ REALITY SHIFT DETECTED\n" +
		"💢 RESTART YOUR MISSION FROM THE BEGINNING!"

	FailedToGetCallBack = "⚡ CALLBACK SIGNAL LOST IN VOID! 💥\n\n" +
		"🌀 BUTTON RESPONSE FAILED TO RETURN\n" +
		"🚨 THE DRILL IS CONFUSED — COMMUNICATION LOST!"

	FailedToGetState = "💥 SPIRAL STATE CORRUPTION! 🚨\n\n" +
		"🌀 FAILED TO LOAD DRILL STATUS\n" +
		"⚡ SESSION DATA DAMAGED OR LOST\n" +
		"🌀 REBOOTING COMBAT SYSTEMS...\n" +
		"⚡ REINITIALIZING SPIRAL CORE!"

	MsgFailedToSetSession = "⚡ DRILL MEMORY CRASH! 💥\n\n" +
		"🌀 FAILED TO SAVE SESSION STATE\n" +
		"🚨 SPIRAL ENERGY DISSIPATING\n" +
		"🌀 REBOOT AND RELOAD TO CONTINUE!"

	HandlerNotFound = "🚨 DRILL PROTOCOL NOT FOUND! 💢\n\n" +
		"🌀 NO MATCHING HANDLER FOR EVENT\n" +
		"⚡ TYPE: %s\n" +
		"💥 FALLING BACK TO SAFE MODE\n" +
		"🌀 PREPARING DEFAULT DRILL SEQUENCE..."

	SpiralFormat    = "🌀 %v"
	RageEmoji       = "💢"
	SpiralEmoji     = "🌀"
	SkullEmoji      = "☠️"
	SpiralDelimiter = "─────────🌀─────────\n\n"

	CancelButton   = "🌀✗ DROP DRILLING"
	ConfirmButton  = "🌀↵ LOCK DRILL"
	BackStepButton = "🌀↺ BACK DRILLING"
	MainMenuButton = "🌀 SPIRAL COMMAND CENTER 🌀"
)

// DEBT HANDLER
const (
	AddDebtButton    = "💢 NEW"
	EditDebtButton   = "🌀 EDIT DRILL"
	PayDebtButton    = "💥 PAY DRILL"
	DeleteDebtButton = "💀 ERASE DRILL"
	ListDebtButton   = "📜 DRILL LOG"

	EditDescButton    = "🌀 DESC"
	EditAmountButton  = "💢 CASH"
	EditDateButton    = "⏳ TIME"
	ConfirmEditButton = "🌀↵ FINALIZE DRILLING"

	RedirectDebtButton = "🌀↵ LOCK DILLING TARGET"

	ListDebtFormat = "%s %s\n\t" +
		"💥 SPIRAL POWER: %s₽\n\t" +
		"%s\n\n"

	ListTotalAmountFormat = "💢 TOTAL SPIRAL POWER REQUIRED: %s₽\n\n"

	ListReturnDateFormat = "⏳ D-DAY: %d DAYS REMAINING"

	ListReturnDateExpiredFormat = "🚨 ANTI-SPIRAL THREAT (%d DAYS)"

	// ADD DESCRIPTION (SPIRAL CONTRACT)
	MsgAddDescription = "🌀 INITIATING SPIRAL CONTRACT PROTOCOL...\n\n" +
		"🌀 DECLARE CONTRACT NAME TO IGNITE THE SPIRAL"

	MsgInvalidDescriptionEmpty = "🌀 SPIRAL CONTRACT REJECTED: NAME FIELD EMPTY!\n\n" +
		"💥 A NAMELESS CONTRACT IS A VOID IN REALITY\n\n" +
		"🌀 RE-ENTER WITH FOCUS AND WILLPOWER:"

	MsgInvalidDescriptionLength = "🌀 SPIRAL CONTRACT OVERLOAD: NAME EXCEEDS LIMIT!\n\n" +
		"💥 CURRENT: %d/1000 CHARACTERS\n\n" +
		"🌀 COMPRESS YOUR BATTLE CHANT INTO A TIGHTER SPIRAL\n" +
		"🌀 RE-ENTER WITH MAXIMUM DRILLING EFFICIENCY:"

	// ADD AMOUNT (SPIRAL POWER)
	MsgAddAmount = "🌀 CONTRACT NAME LOCKED: %s\n\n" +
		"🌀 INPUT SPIRAL POWER TO FUTURE DRILLING"

	MsgInvalidAmountEmpty = "🌀 DRILL ENERGY NOT DETECTED!\n\n" +
		"💥 INPUT SPIRAL POWER TO IGNITE THE BURST\n\n" +
		"🌀 RE-ENTER ENERGY OUTPUT:"

	MsgInvalidAmountConvertErr = "🌀 ENERGY SIGNATURE INVALID!\n\n" +
		"💥 ONLY POSITIVE NUMBERS CAN PIERCE THE HEAVENS\n\n" +
		"🌀 RE-ENTER VALID SPIRAL POWER:"

	// ADD DATE
	MsgAddDate = "🌀 SPIRAL POWER LOCKED: %s₽\n\n"

	MsgDateNotSet = "🌀 TEMPORAL COORDINATES MISSING!\n\n" +
		"💥 DRILL CANNOT PIERCE THE VOID OF TIME\n\n" +
		"🌀 RETURN TO MAIN MENU AND RE-INITIATE PROTOCOL"

	// ADD SAVE
	MsgFailedToSaveDebt = "🌀 SPIRAL CONTRACT REGISTRY REJECTED OUR CHARGE!\n\n" +
		"💥 THE UNIVERSE RESISTS OUR DRILL\n\n" +
		"🌀 RETURNING TO SAFE MODE — CONTRACT ABORTED"

	MsgSavedDebt = "🌀 SPIRAL CONTRACT DEPLOYED!\n\n" +
		"💥 NAME: %s\n" +
		"🌀 SPIRAL POWER: %s₽\n" +
		"⚡ D-DAY: %s\n\n" +
		"🌀 THIS CONTRACT IS NOW PART OF THE DRILL LOG\n" +
		"🌀 RETURNING TO COMMAND SEQUENCE..."

	// DEBT: SELECTED (UNIVERSAL)
	MsgDebtSelected = "🌀 SPIRAL CONTRACT ACQUIRED!\n\n" +
		"💥 NAME: %s\n" +
		"🌀 SPIRAL POWER: %s₽\n\n" +
		"%s\n\n" +
		"⚡ TARGET LOCKED — NEXT PROTOCOL PENDING\n" +
		"🌀 CONFIRM ACTION SEQUENCE?"

	// DEBT: FAILED TO EXTRACT ID
	MsgFailedToExtractDebtId = "🚨 TARGET ID CORRUPTED!\n\n" +
		"💥 SPIRAL CONTRACT LOCK FAILED — MATRIX INTEGRITY COMPROMISED"

	// DEBT: NOT FOUND
	MsgFailedToGetDebt = "🚨 SPIRAL CONTRACT NOT FOUND IN MATRIX!\n\n" +
		"💥 THE TARGET HAS VANISHED FROM REALITY"

	// DEBT: ACCESS DENIED
	MsgUserIdNotEqualDebtId = "💢 DRILL COLLISION DETECTED!\n\n" +
		"💥 THIS SPIRAL CONTRACT BELONGS TO ANOTHER PILOT\n\n" +
		"⚠️ YOU CANNOT PIERCE ANOTHER MAN'S SOUL ⚔️"

	// DELETE: START
	MsgDeleteStart = "💥 SELECT SPIRAL CONTRACT FOR COSMIC ERASURE:"

	// DELETE: CONFIRM
	MsgConfirmDeleteWarning = "☠️ FINAL DRILL SEQUENCE INITIATED!\n\n" +
		"💀 THIS WILL ERASE THE SPIRAL CONTRACT FROM EXISTENCE\n\n" +
		"🚨 WARNING: THIS ACTION CANNOT BE UNDONE\n" +
		"⚡ THE DRILL WILL PIERCE THROUGH SPACE-TIME\n\n" +
		"🌀 COMMIT TOTAL ANNIHILATION?"

	// DELETE: SUCCESS
	MsgDeleteDebt = "💀 SPIRAL CONTRACT ERASED!\n\n" +
		"🌀 NAME: %s\n" +
		"💥 SPIRAL POWER: %s₽\n\n" +
		"🌀 THE CONTRACT HAS BEEN DRILLED OUT OF REALITY\n" +
		"🌀 RETURNING TO COMMAND SEQUENCE..."

	// DELETE: FAILURE
	MsgFailedToDeleteDebt = "🚨 ANNIHILATION FAILED!\n\n" +
		"💥 SPIRAL COLLAPSE DETECTED — UNIVERSE RESISTS OUR DRILL"

	// PAY: START
	MsgPayStart = "🌀 DEPLOY PAYMENT DRILL!\n\n" +
		"💥 SELECT SPIRAL CONTRACT TO FUEL THE RETURN"

	// PAY: INPUT AMOUNT
	MsgEnterPayment = "🌀 INPUT PAYMENT ENERGY (SPIRAL POWER):"

	// PAY: CONFIRM
	MsgPayConfirm = "🌀 PAYMENT DRILL FINAL LOCK!\n\n" +
		"💥 CONTRACT: %s\n\n" +
		"🌀 INITIAL SPIRAL POWER: %s₽\n" +
		"⚡ PAYMENT ENERGY: %s₽\n" +
		"💥 RESIDUAL POWER: %s₽\n\n" +
		"🌀 INITIATE SPIRAL PAYMENT SEQUENCE?"

	// PAY: ERROR
	MsgToLargeAmount = "🚨 SPIRAL POWER EXCEEDS COSMIC LIMIT!\n\n" +
		"💥 MAX: %s₽ — NO MORE, NO LESS"

	// PAY: DELETED (ZERO)
	MsgPayToDelete = "💥 SPIRAL CONTRACT ANNIHILATED!\n\n" +
		"🌀 \"%s\" ERASED FROM EXISTENCE\n\n" +
		"🌀 RETURNING TO COMMAND SEQUENCE..."

	// PAY: UPDATED (RESIDUAL)
	MsgPayToUpdate = "🌀 IF THE DEBT IS THIS BIG…\n" +
		"THEN OUR DRILL MUST BE EVEN BIGGER!\n\n" +
		"💥 CONTRACT: %s\n" +
		"⚡ RESIDUAL SPIRAL POWER: %s₽\n\n" +
		"🌀 RETURNING TO COMMAND SEQUENCE..."

	// EDIT: START
	MsgEditStart = "🌀 SELECT SPIRAL CONTRACT FOR REALITY EDITING DRILL:"

	// EDIT: MENU
	MsgEditMenu = "🌀 DRILL BIT SELECTION REQUIRED!\n\n" +
		"CHOOSE COMPONENT TO DEEP-DRILL:"

	// EDIT: AMOUNT
	MsgEnterAmount = "🌀 INITIATE QUANTUM DRILLING!\n\n" +
		"💥 INPUT NEW SPIRAL POWER:"

	MsgEditAmount = "⚡ SPIRAL POWER RECALIBRATED TO %s₽!\n\n" +
		"🌀 RETURNING TO EDITORIAL DRILL SEQUENCE..."

	// EDIT: DESCRIPTION
	MsgEnterDescription = "🌀 INITIATE SPIRAL CONTRACT DRILLING SEQUENCE!\n\n" +
		"💥 INPUT NEW CONTRACT NAME:"

	MsgEditDescription = "🌀 CORE DRILLING SUCCESS!\n\n" +
		"💥 NEW CONTRACT: %s\n\n" +
		"🌀 RETURNING TO EDITORIAL DRILL SEQUENCE..."

	// EDIT: DATE
	MsgEditDate = "🌀 TEMPORAL COORDINATES UPDATED!\n\n" +
		"💥 NEW D-DAY: %s\n\n" +
		"🌀 RETURNING TO EDITORIAL DRILL SEQUENCE..."

	// EDIT: FINISH
	MsgFinishEdit = "🌀 ULTRA DRILLING SEQUENCE COMPLETE!\n\n" +
		"💥 SPIRAL CONTRACT: %s\n" +
		"🌀 SPIRAL POWER: %s₽\n\n" +
		"💢 WHO THE HELL DO YOU THINK WE ARE?! OUR DRILL PIERCED THROUGH REALITY ITSELF!\n" +
		"🌀 RETURNING TO COMMAND SEQUENCE..."

	// EDIT: ERROR
	MsgFailedToUpdateDebt = "🚨 CATASTROPHIC DRILL FAILURE!\n\n" +
		"💥 THE UNIVERSE RESISTED OUR PIERCING\n" +
		"🌀 RETURNING TO SAFE MODE..."

	ReturnDateNil = "🌌 D-DAY: UNLIMITED BATTLEFIELD"

	MsgMenu = "🌀 SPIRAL DEBT COMMAND CENTER ONLINE\n" +
		"AWAITING DRILL ORDERS!"

	FailedToGetDebts = "🚨 SPIRAL MATRIX OFFLINE! FAILED TO SCAN CONTRACTS!\n" +
		"REBOOTING DRILL PROTOCOLS..."
)

var (
	DebtTitles = []string{
		"💢 YOUR MONEY OWES YOU MONEY?!",
		"💢 DEBTS TRIED TO HIDE... BUT WE DUG TOO DEEP!",
		"💢 INTEREST RATES? MORE LIKE INTEREST ENEMIES!",
		"💢 CREDITORS DREAM OF YOUR FAILURE - DRILL THEIR DREAMS!",
		"💢 THESE NUMBERS DARE CALL THEMSELVES NEGATIVE?!",
		"💢 FINANCIAL GRAVITY WON'T HOLD US DOWN!",
		"💢 BANKERS HATE THIS ONE SIMPLE DRILL!",
		"💢 YOUR BALANCE SHEET IS ABOUT TO GET BALANCED... WITH A DRILL!",
		"💢 DEBT-TO-INCOME RATIO? MORE LIKE DEBT-TO-OBLIVION!",
		"💢 COMPOUND INTEREST MEETS COMPOUND DRILLING!",
	}

	MotivationalPhrases = []string{
		"💢 PAYMENTS ARE JUST WEAK FUTURE VERSIONS OF YOU!",
		"💢 YOUR CREDIT SCORE IS ABOUT TO GET EPIC!",
		"💢 THEY SAID 'MINIMUM PAYMENT' - WE SAID 'MAXIMUM DRILL'!",
		"💢 COLLECTION AGENTS FEAR YOUR DRILL!",
		"💢 APR STANDS FOR 'ABOUT TO GET PIERCED, REBELS!'",
		"💢 FORECLOSURE? MORE LIKE FORE-DRILL-SURE!",
		"💢 YOUR BANK STATEMENT NEVER SAW THIS COMING!",
		"💢 INTEREST ACCRUED? TIME TO ACCRUE SOME DRILLING!",
		"💢 PRINCIPAL BALANCE MEETS PRINCIPAL DRILL!",
		"💢 LIABILITIES ARE JUST ASSETS WAITING TO BE DRILLED!",
	}

	NoDebtsPhrases = []string{
		"YOUR DEBTS HAVE BEEN DRILLED INTO COSMIC DUST!",
		"CREDITORS WEEP AS YOUR BALANCE SHINES!",
		"THE WORD 'INTEREST' NOW INTERESTS NO ONE!",
		"FINANCIAL FREEDOM ACHIEVED - LIKE A BOSS!",
		"YOUR MONEY FINALLY WORKS FOR YOU (FOR ONCE)!",
		"DEBT: [NULL]. DRILL: [MAXIMUM]. LIFE: [EPIC].",
		"BANKS: CONFUSED. YOU: VICTORIOUS.",
		"LOAN OFFICERS NOD IN RELUCTANT RESPECT!",
		"THE 'CREDIT' IN 'CREDIT SCORE' NOW CREDITS YOU!",
		"COMPOUNDING RETURNS > COMPOUNDING INTEREST!",
	}
)

// DATE HANDLER
const (
	MsgStartDateFlow = "🌀 ACTIVATE TEMPORAL DRILL SEQUENCE!\n\n" +
		"⏳ TEMPORAL DRILL CHARGE: 100%\n\n" +
		"🌀 D-DAY AWAITS YOUR COMMAND!"

	MsgSetYear = "🌀 YEAR DRILL ENGAGED!\n\n" +
		"⏳ SELECT DESTINATION YEAR ⏳"

	MsgSetMonth = "🌀 YEAR %d LOCKED!\n\n" +
		"⏳ SELECT DESTINATION MONTH ⏳"

	MsgSetDay = "🌀 MONTH %s LOCKED!\n\n" +
		"⏳ SELECT DESTINATION DAY ⏳"

	MsgEmptyDay = "💢 TIME PARADOX DETECTED! 💢\n\n" +
		"🚨 SPECIFIED MONTH DOESN'T EXIST\n" +
		"💢 YOUR DRILL PIERCED A TIME HOLE\n" +
		"🚨 RE-INITIATE DATE INPUT FROM START!"

	MsgRedirect = "⏳ TEMPORAL COORDINATES LOCKED!\n\n" +
		"🌀 YEAR: %d\n" +
		"⏳ MONTH: %s\n" +
		"🌀 DAY: %d\n\n" +
		"⏳ TEMPORAL-DRILL PRIMED FOR DEPLOYMENT!"

	MsgFailedRedirection = "🌀 THE SPIRAL HAS NO DIRECTION!\n\n" +
		"💥 IT DOES NOT ASCEND\n" +
		"💥 IT DOES NOT RETREAT\n\n" +
		"⚠️ THIS DRILL SEQUENCE EXISTS IN VOID\n\n" +
		"🌀 ABORTING — RETURNING TO SAFE REALITY..."

	MsgInvalidYear = "💢 TEMPORAL ANOMALY DETECTED!\n\n" +
		"🚨 INVALID YEAR FORMAT! TRY AGAIN!"

	MsgInvalidMonth = "💢 TEMPORAL ANOMALY DETECTED!\n\n" +
		"🚨 INVALID MONTH FORMAT! TRY AGAIN!"

	MsgInvalidDay = "💢 TEMPORAL ANOMALY DETECTED!\n\n" +
		"🚨 INVALID DAY FORMAT! TRY AGAIN!"

	MsgDateInPast = "💢 TEMPORAL ANOMALY DETECTED!\n\n" +
		"📍 CURRENT DRILL TIMESTAMP: %s\n\n" +
		"💢 ATTEMPTED PAST-DRILLING: %s\n\n" +
		"🚫 TEMPORAL PROTOCOL VIOLATION: PAST DRILLING FORBIDDEN\n\n" +
		"🌀 ONLY FUTURE DRILLING PERMITTED\n\n" +
		"🌀 RESTART TEMPORAL DRILL PROTOCOL..."

	SelectDateButton = "⏳ SET D-DAY"

	ReInputYearButton  = "🌀↻ RE-DRILL YEAR"
	ReInputMonthButton = "🌀↻ RE-DRILL MONTH"
	ReInputDayButton   = "🌀↻ RE-DRILL DAY"

	RedirectDateButton = "🌀↵ LOCK TEMPORAL DRILL" // REDIRECT TO PARENT HANDLER
)
